# Nombre de la aplicación
spring:
  application:
    name: todo-app
# Driver que vamos a usar y se define un usuario y 
# una contraseña
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
# Se define el nombre de la app
    url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE"
# Se habilita la consola h2, para visualizar en la base
# de datos los elementos que se vayan guardaado
  h2:
    console:
      enabled: true
      path: /h2-console
#Configuraciones de JPA 
  jpa:
    show-sql: true
# Hibernate: permite que cuando la aplicacion arranque
# se creen nuevamente las tablas
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
